In [1]:
import numpy as np        # For numerical operations
import pandas as pd       # For data manipulation and analysis
import matplotlib.pyplot as plt  # For data visualization
%matplotlib inline

# Importing WordCloud for text visualization
from wordcloud import WordCloud

# Importing NLTK for natural language processing
import nltk
from nltk.corpus import stopwords    # For stopwords


# Downloading NLTK data
nltk.download('stopwords')   # Downloading stopwords data
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv(
    '/content/drive/MyDrive/Project/dataset/spam.csv',
    encoding='latin1')

In [5]:
df.head(10)

                                                Body  Label        source
0  \nSave up to 70% on Life Insurance.\nWhy Spend...      1  SpamAssassin
1  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1  SpamAssassin
2  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1  SpamAssassin
3  ##############################################...      1  SpamAssassin
4  I thought you might like these:\n1) Slim Down ...      1  SpamAssassin
5  A POWERHOUSE GIFTING PROGRAM You Don't Want To...      1  SpamAssassin
6  Help wanted.  We are a 14 year old fortune 500...      1  SpamAssassin
7  ReliaQuote - Save Up To 70% On Life Insurance\...      1  SpamAssassin
8  TIRED OF THE BULL OUT THERE?\nWant To Stop Los...      1  SpamAssassin
9  Dear ricardo1 ,\nCOST EFFECTIVE Direct Email A...      1  SpamAssassin

In [7]:
styled_df = df.head()
styled_df = styled_df.style.set_table_styles([
    {"selector": "th", "props": [("color", 'black'), ("background-color", "#FFFFFF")]}
])
styled_df

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17570 entries, 0 to 17569
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Body    17570 non-null  object
 1   Label   17570 non-null  int64
 2   source  17570 non-null  object
dtypes: int64(1), object(2)
memory usage: 411.9+ KB

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['Label'])

In [11]:
df.drop('Label', axis=1, inplace=True)

In [13]:
styled_df = df.head().style


# Modify the color and background color of the table headers (th)
styled_df.set_table_styles([
    {"selector": "th", "props": [("color", 'Black'), ("background-color", "#FFFFFF"), ('font-weight', 'bold')]}
])

In [14]:
df.isnull().sum()

Body      0
source    0
target    0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.shape

(17570, 3)

### EDA